import type { Metadata } from "next";
import { ABeeZee } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import { Analytics } from '@vercel/analytics/react';

const abeezee = ABeeZee({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Find Space",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${abeezee.className} bg-white`}>
        <Navbar/>
        {children}
        <Analytics />
        <Footer/>
        </body>
    </html>
  );
}
